config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as:'home'
  get 'about' => 'pages#about', as: 'about'

  get '/auth', to: 'auth#new'
  post '/auth', to: 'auth#create'
  delete '/auth', to: 'auth#destroy'

  get '/users', to: 'users#new'
  post '/users', to: 'users#create'

  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :body

  #maby
  # after_create :some
  #
  # def some
  #
  # end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true, length:{minimum: 5}
  has_many :comments
  belongs_to :user
  #maby
  # after_create :some_animation
  #
  # def some_animation
  #
  # end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence:true, uniqueness: true
  validates :name, presence:true
  # before_validation :normalize_name, on: :create
  #after_validation :set_location, on: [:create,:update]

  has_many :posts
  has_secure_password

  def normalize_name
    self.name = name.downcase.titleize
  end
  def set_location
    self.location = LocationService.query(self)
  end

  after_initialize do |user|
    puts "You have initialized an user!"
  end
  after_find do |user|
    puts "You have found an user!"
  end
end

app/controllers/Fixtures.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'json'

url = URI("https://v3.football.api-sports.io/leagues")

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Get.new(url)
request["x-rapidapi-host"] = 'v3.football.api-sports.io'
request["x-rapidapi-key"] = '21156322e71ca970ba5b42583049c570'

response = http.request(request)
arr = JSON.parse(response.read_body)

ar = eval(arr["response"].to_s)
ar.map do |x|
  p x["league"]
end
#ar["league"]["name"].each do |x|
#puts x
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user

  def authorise_user
    redirect_to auth_path unless @current_user
  end


  def render_not_found
     render file: "#{Rails.root}/public/404.html",
                  layout: true,
                  status: :not_found
  end
  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id].present?
  end



  def user_signed_in?
    current_user.present?
  end
   helper_method :current_user,:user_signed_in?
end

app/controllers/aurh_controller.rb
class UsersController < ApplicationController
  #  http_basic_authenticate_with name: "admin", password: "123", except: [:index, :show]

  def create
    @user = User.find_by_email(user_params[:email])
    return redirect_to auth_path,alert: 'Wrong credentials' unless @user
    if @user&.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirected_to feed_path
    else
      redirected_to auth_path,alert: @user.errors.full_messages.join
    end
  end
  def destroy

  end
  private def user_params
    params.require(:user).permit(:email, :password)
  end



end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  #  http_basic_authenticate_with name: "admin", password: "123", except: [:index, :show]

  def new
    @user =User.new
  end

  def create
    @user = User.find_by_email(user_params[:email])
    return redirect_to auth_path,alert: 'Wrong credentials' unless @user
    #if @user.password == params[:password]
    if @user&.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to home_path
    else
      redirect_to auth_path,alert: @user.errors.full_messages.join
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path
  end

  private def user_params
    params.require(:user).permit(:email, :password)
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "123"
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страница про нас!'
    @text = 'На этом сайте вы можете составлять собственные прогнозы на спорт'
    @league = "140"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "123", except: [:index, :show]

  before_action :set_post, only: [:show]
  before_action :authorise_user, only: %i[new create edit update destroy]
  before_action :authorize_post, only: %i[edit, update, destroy]
  def index  #Обработка главной страницы
    @post = Post.all
  end

  def new   #Создаем статью
    @post = Post.new;
  end

  def show
    return render_not_found unless @post.user == @current_user
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create #Работа кнопки сохранить статью
    #render plain:params[:post].inspect
    @post = @current_user.posts.create(post_params)
    @post.save    #Сохраняем пост
    if @post.save
      redirect_to @post #Перемещаем пользователя на новую страницу
    else
      render 'new'
    end
  end

  private

  def authorize_post
    render_not_found unless @post.user == @current_user
  end

  private

  def set_post
    @post= Post.find_by_id(params[:id])
  end


  def post_params   #Описываем какие параметры разрешено использовать в Post
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id

      redirect_to home_path
    else
      render :new, alert: @user.errors.full_messages.join
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:name,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_errors.html.erb
<% flash.each do |_,msg| %>
<div >
  <%= msg %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm ">
    <span class="my-0 mr-md-auto font-weight-bold" >
      <%=link_to "SportForecasts", home_path %></span>
    <span class="p-2 text-dark"><%= link_to "Добавление статьи", new_post_path %></span>
      <span class="p-2 text-dark"><%= link_to "О нас", about_path %></span>
    <%- if @current_user#user_signed_in?  %>
      <%=@current_user.name %>
      <span class="p-2 text-dark"><%= link_to "Выйти", auth_url, method: :delete%></span>
      <%-else %>
    <span class="p-2 text-dark"><%= link_to "Войти", auth_url %></span>
      <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StavkiProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold">SportForecasts</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark" ><%= link_to "Главная страница", home_path %></span>
      <span class="p-2 text-dark" ><%= link_to "О нас", about_path %></span>
    </nav>
    <span class="p-2 text-dark" ><%= link_to "Добавление статьи", new_post_path %></span>
  </div>

    <div class ="container">

    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%=form_for :post, url:post_path(@post), method: :patch do |f| %>
  <%if @post.errors.any? %>
    <%@post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Название<br>
    <%=f.text_field(:title, {:class =>'form-control'} ) %>
  </p>
  <p>
    Текст статьи<br>
    <%=f.text_area(:body, {:class =>'form-control'} )%>
  </p>

  <p>
    <%=f.submit("Сохранить",{:class =>'btn btn-success'} )%>
  </p>
<%end %>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>

<% @post.each do|post| %>
  <div  class="alert alert-light">
    <h3><%=post.title %></h3>
    <p class="clip"><%=post.body %></p>

    <%=link_to "Читать далее" , post_path(post), :class =>'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%=form_for :post, url:posts_path do |f| %>
  <%if @post.errors.any? %>
    <%@post.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%=msg %></div>
    <%end %>
  <%end %>
   <p>
    Название<br>
    <%=f.text_field(:title, {:class =>'form-control'} ) %>
   </p>
  <p>
    Текст статьи<br>
    <%=f.text_area(:body, {:class =>'form-control'} )%>
  </p>

  <p>
    <%=f.submit({:class =>'btn btn-success'} )%>
  </p>
<%end %>
<p>
  <h5><%= "Выберите день матча" %></h5>
  <%= date_field(:reservation, :arrival_date) %>
</p>
<label for="league_name"></label><select name="league[name]" id="league_name">
  <option value="140" selected="selected">La Liga</option>
  <option value="39">Premier League</option>
  <option value="78">Bundesliga 1</option>
</select>
<br>

<div id="wg-api-football-fixtures"
     data-host="v3.football.api-sports.io"
     data-refresh="60"
     data-date=""
     data-league=<%= @league %>
     data-team = ""
     data-season="2021"
     data-last=""
     data-next="15"
     data-key="21156322e71ca970ba5b42583049c570"
     data-theme=""
     data-show-errors="false"
     class="api_football_loader">
</div>
<script
  type="module"
  src="https://widgets.api-sports.io/football/1.1.8/widget.js">
</script>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p class ="show_text "><%=@post.body %></p>
<hr>
<% if @current_user  %>
<%=link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%=link_to "Удалить пост", post_path(@post),method: :delete, data: {confirm: "Хотите удалить статью?"}, :class => 'btn btn-danger' %>
<% end %>
<hr>

<h2>Все комментарии</h2>
<% @post.comments.each do|comment| %>
  <div  class="alert alert-light">
    <p><strong><%=@current_user.name%></strong>:<%=comment.body %></p>
  </div>
<% end %>

<hr>
<h2>Добавление комментария</h2>
<%=form_for([@post, @post.comments.build]) do |f| %>


  <p>
  <%= @current_user.name %>:<br>
    Текст комментария<br>
    <%=f.text_area(:body, {:class =>'form-control'} )%>
  </p>

  <p>
    <%=f.submit("Добавить комментарий",{:class =>'btn btn-success'} )%>
  </p>
<%end %>

app/views/users/_form.html.erb
<%= form_with  model: @user, url: auth_url do |f| %>
  <div class="md-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>

    <div class="col-sm-10">
      <%= f.email_field :email, placeholder: 'E-mail', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="md-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Имя', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="md-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, placeholder: 'Пароль', class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="md-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, placeholder: 'Повторите пароль', class: 'form-control form-control-lg' %>
    </div>
  </div>
  <%= f.submit "Регистрация", class: 'btn btn-success btn-lg' %>
<%end%>

app/views/users/new.html.erb
<%= provide :page_title, 'Регистрация' %>

<h1 class="mb-4">Регистрация</h1>
<%=render 'users/form' %>
<%= link_to 'Вход',auth_url%>